name: CI / CD

on:
  push:
    branches:
      - testCI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: testCI
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm install
          npm run build --if-present
      - name: Commit the build folder and push
        uses: EndBug/add-and-commit@v4
        with:
          add: build
          force: True
          message: 'chore: new build'
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Commit the build folder
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git commit -am "chore: new build"
      #   with:
      #     commit_message: "chore: new build"
      #     file_pattern: build/**/*
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: testCI