name: CI / CD

on:
  push:
    branches:
      - testCI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: testCI
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: SSH-Agent
      #   uses: webfactory/ssh-agent@v0.1.1
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build
        run: |
          npm install
          npm run build --if-present
      # - name: Semantic Release
      #   run: npx semantic-release
      - name: Commit the build folder and push
        uses: EndBug/add-and-commit@v4
        with:
          add: build
          force: True
          message: ${{ github.event.commits[0].message }}
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: testCI